--------------------------------------------------------
--  File created - Monday-April-21-2025
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASSES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CLASSES"
   (	"CLASS_ID" NUMBER(*,0),
	"DAY_OF_WEEK" NUMBER(*,0),
	"GROUP_NR" NUMBER(*,0),
	"COURSE_ID" NUMBER(*,0),
	"CLASSROOM" NUMBER(*,0),
	"CLASS_TYPE" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	"START_TIME" TIMESTAMP (6),
	"END_TIME" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table COMPLETION_REQUIREMENTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COMPLETION_REQUIREMENTS"
   (	"COMPLETION_REQ_ID" NUMBER(19,0),
	"MIN_SCORE" NUMBER(10,0),
	"TYPE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COURSES"
   (	"COURSE_ID" NUMBER(*,0),
	"NAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ECTS_POINTS" NUMBER(*,0),
	"STATUS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table COURSES_SPECIAL
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COURSES_SPECIAL"
   (	"COURSE_ID" NUMBER(*,0),
	"SPECIALIZATION_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table COURSE_LECTURERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COURSE_LECTURERS"
   (	"COURSE_ID" NUMBER(*,0),
	"LECTURER_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table COURSE_REGISTRATIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COURSE_REGISTRATIONS"
   (	"COURSE_ID" NUMBER(19,0),
	"COURSE_REG_ID" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"STATUS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"STUDENT_ID" NUMBER(19,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table COURSE_REQUIREMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."'COURSE_REQUIREMENT'"
   (	"COURSE_ID" NUMBER(*,0),
	"COMPLETION_REQ_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table ENROLL_REQUIREMENTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ENROLL_REQUIREMENTS"
   (	"REG_ID" NUMBER(19,0),
	"COURSE_ID" NUMBER(19,0),
	"MIN_ECTS" NUMBER(10,0),
	"COMPLITED_COURSE_ID" NUMBER(19,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table GRADES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."GRADES"
   (	"GRADE_ID" NUMBER(*,0),
	"GRADE" NUMBER(4,2),
	"RECEIVED_DATE" DATE,
	"LECTURER_ID" NUMBER(*,0),
	"COURSE_ID" NUMBER(*,0),
	"STUDENT_ID" NUMBER(*,0),
	"TYPE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"RECORDED" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table LECTURERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LECTURERS"
   (	"USER_ID" NUMBER(*,0),
	"ACADEMIC_TITLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ROLES"
   (	"ROLE_ID" NUMBER(*,0),
	"ROLE_NAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table SEMESTER_ECTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SEMESTER_ECTS"
   (	"SEMESTER_ECTS_ID" NUMBER(*,0),
	"SEMESTER" NUMBER(*,0),
	"ECTS_AMOUNT" NUMBER(*,0),
	"SPECIALIZATION_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table SPECIALIZATIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SPECIALIZATIONS"
   (	"SPECIALIZATION_ID" NUMBER(*,0),
	"NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."STUDENTS"
   (	"USER_ID" NUMBER(*,0),
	"STUDENT_NUMBER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"STATUS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"LIBRARY_CARD_NUMBER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table STUDENT_SPECIALIZATIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."STUDENT_SPECIALIZATIONS"
   (	"SPECIALIZATION_ID" NUMBER(*,0),
	"STUDENT_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."USERS"
   (	"USER_ID" NUMBER(*,0),
	"FIRST_NAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"LAST_NAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"EMAIL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"PASSWORD" VARCHAR2(255) COLLATE "USING_NLS_COMP",
	"ROLE" VARCHAR2(255)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

--------------------------------------------------------
--  Constraints for Table COURSE_LECTURERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURSE_LECTURERS" ADD PRIMARY KEY ("COURSE_ID", "LECTURER_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE_REQUIREMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURSE_REQUIREMENT" ADD PRIMARY KEY ("COURSE_ID", "COMPLETION_REQ_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRADES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."GRADES" ADD PRIMARY KEY ("GRADE_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_SPECIALIZATIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."STUDENT_SPECIALIZATIONS" ADD PRIMARY KEY ("SPECIALIZATION_ID", "STUDENT_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ROLES" ADD PRIMARY KEY ("ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."ROLES" ADD UNIQUE ("ROLE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LECTURERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LECTURERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURSES" ADD PRIMARY KEY ("COURSE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."COURSES" ADD CONSTRAINT "UNIQUE_COURSE_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLL_REQUIREMENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ENROLL_REQUIREMENTS" ADD PRIMARY KEY ("REG_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."ENROLL_REQUIREMENTS" ADD CONSTRAINT "UKPI85T8YNHEFQ7WAIBTJ8UOXTE" UNIQUE ("COMPLITED_COURSE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."ENROLL_REQUIREMENTS" MODIFY ("REG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSES_SPECIAL
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURSES_SPECIAL" ADD PRIMARY KEY ("COURSE_ID", "SPECIALIZATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPECIALIZATIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SPECIALIZATIONS" ADD PRIMARY KEY ("SPECIALIZATION_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."STUDENTS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."STUDENTS" ADD UNIQUE ("STUDENT_NUMBER")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPLETION_REQUIREMENTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COMPLETION_REQUIREMENTS" ADD PRIMARY KEY ("COMPLETION_REQ_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ADMIN"."COMPLETION_REQUIREMENTS" MODIFY ("MIN_SCORE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMPLETION_REQUIREMENTS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."COMPLETION_REQUIREMENTS" MODIFY ("COMPLETION_REQ_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASSES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CLASSES" ADD PRIMARY KEY ("CLASS_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE_REGISTRATIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURSE_REGISTRATIONS" MODIFY ("COURSE_REG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEMESTER_ECTS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SEMESTER_ECTS" ADD PRIMARY KEY ("SEMESTER_ECTS_ID")
  USING INDEX  ENABLE;

-------- Foregin keys
-- USERS → ROLES
ALTER TABLE USERS
  ADD CONSTRAINT FK_USERS_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID);

-- STUDENTS → USERS
ALTER TABLE STUDENTS
  ADD CONSTRAINT FK_STUDENTS_USER
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- LECTURERS → USERS
ALTER TABLE LECTURERS
  ADD CONSTRAINT FK_LECTURERS_USER
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- STUDENT_SPECIALIZATIONS → STUDENTS, SPECIALIZATIONS
ALTER TABLE STUDENT_SPECIALIZATIONS
  ADD CONSTRAINT FK_STUDSPEC_STUDENT
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(USER_ID);

ALTER TABLE STUDENT_SPECIALIZATIONS
  ADD CONSTRAINT FK_STUDSPEC_SPEC
  FOREIGN KEY (SPECIALIZATION_ID) REFERENCES SPECIALIZATIONS(SPECIALIZATION_ID);

-- COURSES_SPECIAL → COURSES, SPECIALIZATIONS
ALTER TABLE COURSES_SPECIAL
  ADD CONSTRAINT FK_COURSPECIAL_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

ALTER TABLE COURSES_SPECIAL
  ADD CONSTRAINT FK_COURSPECIAL_SPEC
  FOREIGN KEY (SPECIALIZATION_ID) REFERENCES SPECIALIZATIONS(SPECIALIZATION_ID);

-- COURSE_LECTURERS → COURSES, LECTURERS
ALTER TABLE COURSE_LECTURERS
  ADD CONSTRAINT FK_COURSELEC_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

ALTER TABLE COURSE_LECTURERS
  ADD CONSTRAINT FK_COURSELEC_LECTURER
  FOREIGN KEY (LECTURER_ID) REFERENCES LECTURERS(USER_ID);

-- COURSE_REQUIREMENT → COURSES, COMPLETION_REQUIREMENTS
ALTER TABLE COURSE_REQUIREMENT
  ADD CONSTRAINT FK_COURSE_REQ_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

ALTER TABLE COURSE_REQUIREMENT
  ADD CONSTRAINT FK_COURSE_REQ_REQ
  FOREIGN KEY (COMPLETION_REQ_ID) REFERENCES COMPLETION_REQUIREMENTS(COMPLETION_REQ_ID);

-- COURSE_REGISTRATIONS → COURSES, STUDENTS
ALTER TABLE COURSE_REGISTRATIONS
  ADD CONSTRAINT FK_COURSE_REG_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

ALTER TABLE COURSE_REGISTRATIONS
  ADD CONSTRAINT FK_COURSE_REG_STUDENT
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(USER_ID);

-- ENROLL_REQUIREMENTS → COURSES, COMPLETED COURSE
ALTER TABLE ENROLL_REQUIREMENTS
  ADD CONSTRAINT FK_ENROLL_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

ALTER TABLE ENROLL_REQUIREMENTS
  ADD CONSTRAINT FK_ENROLL_COMPLETED
  FOREIGN KEY (COMPLITED_COURSE_ID) REFERENCES COURSES(COURSE_ID);

-- GRADES → COURSES, STUDENTS, LECTURERS
ALTER TABLE GRADES
  ADD CONSTRAINT FK_GRADES_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

ALTER TABLE GRADES
  ADD CONSTRAINT FK_GRADES_STUDENT
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(USER_ID);

ALTER TABLE GRADES
  ADD CONSTRAINT FK_GRADES_LECTURER
  FOREIGN KEY (LECTURER_ID) REFERENCES LECTURERS(USER_ID);

-- CLASSES → COURSES
ALTER TABLE CLASSES
  ADD CONSTRAINT FK_CLASSES_COURSE
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID);

-- SEMESTER_ECTS → SPECIALIZATIONS
ALTER TABLE SEMESTER_ECTS
  ADD CONSTRAINT FK_SEMESTER_ECTS_SPEC
  FOREIGN KEY (SPECIALIZATION_ID) REFERENCES SPECIALIZATIONS(SPECIALIZATION_ID);
