CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE USERS(
    USER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR2 (80) NOT NULL,
    LAST_NAME VARCHAR2 (80) NOT NULL,
    EMAIL VARCHAR2 (255),
    PASSWORD_HASH VARCHAR2(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);